### ISSUE TITLE
Missing NVIDIA GPU driver

### ISSUE THREAD

**Issue by strongestFairy** [giuliano-oliveira/baka_mitai_meme_generator#2]
I'm trying to run this code on VPS but get an error.

> AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

Is it possible to run it without NVIDIA GPU hardware?

**Comment by giuliano-macedo** [comment]
I'm pretty sure there is a way to run in the CPU, i will add a flag

**Comment by giuliano-macedo** [comment]
there you go, be aware that it's pretty slow, in my xeon e5450 it would take ~7 hours to predict.

**Comment by strongestFairy** [comment]
It works! On my i5-6500 it took less then 20 minutes.
Thank you very much!
